/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.teoria.junit

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun testSomeLibraryMethod() {

    }
}
